
package org.fabric3.samples.bigbank.api.loan;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "LoanService", targetNamespace = "http://loan.api.bigbank.samples.fabric3.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LoanService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "apply", targetNamespace = "http://loan.api.bigbank.samples.fabric3.org/", className = "org.fabric3.samples.bigbank.api.loan.Apply")
    @ResponseWrapper(localName = "applyResponse", targetNamespace = "http://loan.api.bigbank.samples.fabric3.org/", className = "org.fabric3.samples.bigbank.api.loan.ApplyResponse")
    public void apply(
        @WebParam(name = "arg0", targetNamespace = "")
        LoanApplication arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.fabric3.samples.bigbank.api.loan.LoanApplicationStatus
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://loan.api.bigbank.samples.fabric3.org/", className = "org.fabric3.samples.bigbank.api.loan.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://loan.api.bigbank.samples.fabric3.org/", className = "org.fabric3.samples.bigbank.api.loan.GetStatusResponse")
    public LoanApplicationStatus getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
